### ISSUE TITLE
Collisions between vehicles

### ISSUE THREAD

**Issue by hz-ants** [fast-fire/ColAG#1]
How to solve the problem of two cars colliding, as shown below：
![Collisions](https://github.com/fast-fire/ColAG/assets/51619755/8dfd0058-ef5e-4b4c-96d4-ca527df0d467)

**Comment by South-River** [comment]
The car model makes you feel they are colliding, but actually they are not.
In the field experiments, you can modify the param in Ground_WS related to reciprocal collision avoidance by making it larger. 
You can see the ego planner swarm for more details.

**Comment by zhehanli66** [comment]
This may be that the ugvs are not broadcasting each other's trajectory properly resulting in no mutual avoidance, try modifying the `broadcast_ip` in [run_in_sim.launch](https://github.com/fast-fire/ColAG/blob/main/Ground_ws/src/planner/plan_manage/launch/run_in_sim.launch)

**Comment by zhehanli66** [comment]
Closing this issue due to lack of updated replies.
